# Generated by Django 2.0 on 2017-12-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('street_name', models.CharField(max_length=100)),
                ('street_number', models.CharField(max_length=10)),
                ('additional', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
