# Generated by Django 2.0 on 2018-01-09 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20171221_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name': 'Vendor', 'verbose_name_plural': 'Vendors'},
        ),
    ]
