# Generated by Django 2.0 on 2018-01-09 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_auto_20180109_1034'),
        ('common', '0002_auto_20180109_1034'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customers.Customer')),
                ('product', models.ManyToManyField(related_name='orders', to='products.Product')),
            ],
        ),
    ]
